name: ci-wf
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Step
        run: echo "Welcome To GH Actions"
      - name: Checkout Repository
        uses: actions/checkout@v4

    